from pathlib import Path
from src.pizza import Menu, Pizza, total_with_tax

m = Menu.from_yaml("data/menu.yaml")

# Build a simple sample order for the page
pizzas = [Pizza("large", ["pepperoni", "onions"]), Pizza("medium", ["mushrooms"])]
summary = total_with_tax(m, pizzas, "LARGE2")

rows_menu = []
for size, price in m.sizes.items():
    rows_menu.append(f"<tr><td>{size.title()}</td><td>${price:.2f}</td></tr>")

rows_toppings = []
for t, price in m.toppings.items():
    rows_toppings.append(f"<tr><td>{t.replace('_',' ').title()}</td><td>${price:.2f}</td></tr>")

html = """<!doctype html><html><head>
<meta charset="utf-8"><title>{shop} — Menu & Sample Order</title>
<style>
body{{font-family:system-ui;margin:2rem}}
table{{border-collapse:collapse;width:100%}}
td,th{{border:1px solid #ddd;padding:.6rem;text-align:left}}
th{{background:#f6f6f6}}
code{{background:#f0f0f0;padding:0 .25rem;border-radius:4px}}
</style></head><body>
<h1>{shop}</h1>
<p>Tax rate: {tax:.1f}%</p>

<h2>Menu — Sizes</h2>
<table><thead><tr><th>Size</th><th>Price</th></tr></thead>
<tbody>
{rows_menu}
</tbody></table>

<h2>Menu — Toppings</h2>
<table><thead><tr><th>Topping</th><th>Price</th></tr></thead>
<tbody>
{rows_toppings}
</tbody></table>

<h2>Sample Order (Promo: <code>LARGE2</code>)</h2>
<ul>
  <li>Subtotal: ${subtotal:.2f}</li>
  <li>Discount: -${discount:.2f}</li>
  <li>Total (with tax): ${total:.2f}</li>
</ul>

<p><em>Generated by build_site.py</em></p>
</body></html>
""".format(
    shop=m.shop.get("name","Pizza Shop"),
    tax=float(m.shop.get("tax_rate",0.0))*100.0,
    rows_menu="\n".join(rows_menu),
    rows_toppings="\n".join(rows_toppings),
    subtotal=summary["subtotal"],
    discount=summary["discount"],
    total=summary["total"],
)

Path("docs").mkdir(exist_ok=True)
Path("docs/index.html").write_text(html, encoding="utf-8")
print("Wrote docs/index.html")
